// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sacrament_Meeting_Planner.Data;

#nullable disable

namespace Sacrament_Meeting_Planner.Migrations
{
    [DbContext(typeof(Sacrament_Meeting_PlannerContext))]
    [Migration("20240403201333_UpdateMeetingHymnsToStrings")]
    partial class UpdateMeetingHymnsToStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Sacrament_Meeting_Planner.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Benediction")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conducting")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntermediateHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Invocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presiding")
                        .HasColumnType("TEXT");

                    b.Property<string>("SacramentHymn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerSubject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Sacrament_Meeting_Planner.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("Sacrament_Meeting_Planner.Models.Speaker", b =>
                {
                    b.HasOne("Sacrament_Meeting_Planner.Models.Meeting", "Meeting")
                        .WithMany("Speakers")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("Sacrament_Meeting_Planner.Models.Meeting", b =>
                {
                    b.Navigation("Speakers");
                });
#pragma warning restore 612, 618
        }
    }
}
